# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(default='default_short', max_length=16),
            preserve_default=False,
        ),
    ]
